In [ ]:
import yfinance as yf
import numpy as np
import pandas as pd

In [ ]:
main = pd.DataFrame(yf.download('NQ=F', start = '2023-01-01', end = '2023-12-31')['Close']).reset_index()

main.rename(columns= {'Close' : 'Nasdaq'}, inplace = True)

main.head(5)

[*********************100%%**********************]  1 of 1 completed


Date    Nasdaq
0 2023-01-03  10945.50
1 2023-01-04  10999.25
2 2023-01-05  10820.25
3 2023-01-06  11113.50
4 2023-01-09  11185.50

In [ ]:
normalized = main.copy()

for i in normalized.columns[1:]:
  normalized[i] = normalized[i] / normalized[i][0]

normalized

Date    Nasdaq
0   2023-01-03  1.000000
1   2023-01-04  1.004911
2   2023-01-05  0.988557
3   2023-01-06  1.015349
4   2023-01-09  1.021927
..         ...       ...
246 2023-12-22  1.551322
247 2023-12-26  1.560778
248 2023-12-27  1.563496
249 2023-12-28  1.561418
250 2023-12-29  1.555297

[251 rows x 2 columns]

In [ ]:
return_rate = normalized.copy().drop(columns = ['Date'])

return_rate = np.log(1 + return_rate.pct_change())

display(return_rate)

Nasdaq
0         NaN
1    0.004899
2   -0.016408
3    0.026741
4    0.006458
..        ...
246  0.001385
247  0.006077
248  0.001740
249 -0.001330
250 -0.003928

[251 rows x 1 columns]

In [ ]:
mean = return_rate.mean()
var = return_rate.var()

In [ ]:
drift = mean - 0.5 * var
drift.values

array([0.00170258])

In [ ]:
days = 10
simulations = 5

In [ ]:
from scipy import stats

In [ ]:
rand = np.random.rand(days, simulations)
rand

array([[0.16415047, 0.14093911, 0.66803271, 0.19655945, 0.64228876],
       [0.12538301, 0.13027069, 0.45476949, 0.1003646 , 0.93787841],
       [0.02035344, 0.07401824, 0.98705973, 0.05281263, 0.34049742],
       [0.86063608, 0.72969055, 0.9043995 , 0.6767792 , 0.50031925],
       [0.10566973, 0.59121078, 0.50351394, 0.33468691, 0.20925035],
       [0.70601036, 0.24344962, 0.82239941, 0.91675082, 0.57669527],
       [0.69395329, 0.45008641, 0.73580938, 0.9751197 , 0.27721389],
       [0.69708517, 0.46801686, 0.25894157, 0.77245914, 0.90331775],
       [0.26217974, 0.46610138, 0.29175097, 0.36619675, 0.09549557],
       [0.37888669, 0.22208546, 0.28251335, 0.60373534, 0.43695355]])

In [ ]:
z = stats.norm.ppf(rand)
z

array([[-9.77541917e-01, -1.07610965e+00,  4.34487339e-01,
        -8.53974909e-01,  3.64583302e-01],
       [-1.14849078e+00, -1.12511244e+00, -1.13620064e-01,
        -1.27947681e+00,  1.53720470e+00],
       [-2.04650318e+00, -1.44650189e+00,  2.22799975e+00,
        -1.61817328e+00, -4.11105957e-01],
       [ 1.08318159e+00,  6.11877378e-01,  1.30703450e+00,
         4.58711170e-01,  8.00235469e-04],
       [-1.24989074e+00,  2.30660654e-01,  8.80825492e-03,
        -4.27007562e-01, -8.09025105e-01],
       [ 5.41766640e-01, -6.95249038e-01,  9.24547788e-01,
         1.38354326e+00,  1.93446306e-01],
       [ 5.07087501e-01, -1.25443039e-01,  6.30479010e-01,
         1.96201614e+00, -5.91138257e-01],
       [ 5.16035428e-01, -8.02559258e-02, -6.46611913e-01,
         7.46969907e-01,  1.30069028e+00],
       [-6.36639812e-01, -8.50737504e-02, -5.48276663e-01,
        -3.41943391e-01, -1.30765270e+00],
       [-3.08406054e-01, -7.65168996e-01, -5.75391271e-01,
         2.63027587e-01

In [ ]:
std = return_rate.std()

std

Nasdaq    0.011321
dtype: float64

In [ ]:
r = np.exp(drift.values + std.values * z)
r

array([[0.99067943, 0.98957455, 1.00664343, 0.99206628, 1.0058471 ],
       [0.98876399, 0.98902572, 1.00041636, 0.98729883, 1.01928912],
       [0.97876265, 0.98543371, 1.02729179, 0.98352037, 0.99705276],
       [1.01406337, 1.00866706, 1.01663653, 1.00691953, 1.00171311],
       [0.98762958, 1.00432323, 1.00180393, 0.99687328, 0.99257125],
       [1.00786676, 0.99385058, 1.01224384, 1.01751749, 1.00390019],
       [1.00747115, 1.00028247, 1.00887949, 1.02420303, 0.99502267],
       [1.00757321, 1.00079431, 0.99439797, 1.01021089, 1.01656352],
       [0.99451024, 1.00073973, 0.99550561, 0.99783375, 0.98698395],
       [0.99821268, 0.99306418, 0.99520007, 1.00469132, 0.99990595]])

In [ ]:
predictions = np.zeros_like(r)
predictions

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
for i in range(predictions.shape[0]):

  predictions[i][0] = main['Nasdaq'].iloc[-1]
  predictions[i][0]  = predictions[i][0] * r[i][0]

  for j in range(1, predictions.shape[1]):

    predictions[i][j] = predictions[i][j - 1] * r [i][j]

In [ ]:
predictions = predictions.T
predictions

array([[16864.83129911, 16832.22383737, 16661.96602484, 17262.90777993,
        16812.91220399, 17157.41982911, 17150.68503996, 17152.42250018,
        16930.0450198 , 16993.07359515],
       [16689.00788859, 16647.5023442 , 16419.26293073, 17412.52635682,
        16885.59836248, 17051.91159749, 17155.52954482, 17166.04685432,
        16942.56861139, 16875.21277297],
       [16799.88015099, 16654.4337499 , 16867.37400863, 17702.21042134,
        16916.05873067, 17260.69242895, 17307.86196662, 17069.88210841,
        16866.42213176, 16794.21294892],
       [16666.59457226, 16442.90303076, 16589.40584526, 17824.70141134,
        16863.16696553, 17563.05640383, 17726.7646982 , 17244.18076631,
        16829.88529354, 16872.99989978],
       [16764.0457637 , 16760.07216646, 16540.51285006, 17855.23702873,
        16737.89472719, 17631.55573652, 17638.53272493, 17529.80504449,
        16610.82672993, 16871.41303972]])

In [ ]:
test = pd.DataFrame()

test['Nasdaq'] = yf.download('NQ=F', start = '2024-01-01', end = '2024-01-17')['Close']

test = test.reset_index().drop(columns = ['Date'])

[*********************100%%**********************]  1 of 1 completed


In [ ]:
import plotly.express as px

In [ ]:
test

Nasdaq
0  16720.00
1  16538.00
2  16445.00
3  16460.25
4  16803.75
5  16830.25
6  16945.25
7  16966.25
8  16969.25
9  16966.50

In [ ]:
fig = px.line(title = 'Predictions x Real Price')
fig.add_scatter(y = test.Nasdaq, name = 'Real Price')
for i in range(predictions.shape[0]):
  fig.add_scatter(y = predictions[i], name = f'Pred {i+1}')

fig.show()

In [ ]:
from sklearn.metrics import mean_absolute_error

In [ ]:
errors = []

for i in range(len(predictions)):
  errors.append(mean_absolute_error(test.Nasdaq.values, predictions[i]))

errors

[225.239708984354,
 195.00628564546167,
 314.47584848213484,
 374.18932941285965,
 433.41268180475925]